### ISSUE TITLE
Channel landing page

### ISSUE THREAD

**Issue by RocketSH** [DC7806/Goodbytes#102]
- [x] 文章列表
    - [x] 文章點進去要渲染成給別人看的樣子，而非編輯器
    - [x] channel#landing 給別人看的
    - [x] article#show改成給別人看的
    - [x] 原本的編輯器改成article#edit
    - [x] 原edit功能僅只改標題，所以需要改成switch模式，並打ajax to article#update
        - [x] switch模式：點一下編輯鈕，編輯鈕變成submit（綠）與返回(白），標題變成text field可編輯
- [x] 訂閱按鈕（含輸入email的input）

**Comment by koten0224** [comment]
這pr我只會先弄出基本功能
含按鈕跟email輸入框
以及基本可以顯示出頻道名稱與文章列表
美化會先擺爛（不過還是會用基本bootstrap先排整齊），等另外開票
