### ISSUE TITLE
文章編輯器重構 - 樣板

### ISSUE THREAD

**Issue by koten0224** [DC7806/Goodbytes#105]
此issue等到 #88 merge後再動
因為那個pr已經有點大，審完前不想再去動那條branch
怕越改越大條，且動過後又要再重審
故另外開票

- [x] 現有樣板選單是純文字條列，改成跟原網站類似的樣板示意圖
    - [x] 圖片放在assets
    - [x] 圖名要跟樣板名一致以便在views可以動態指定圖片`"assets/images/#{content.layout}.jpg"`
- [x] 有圖片的樣板在新建時有個預設的holder

**Comment by ErenWeng** [comment]
弄圖片跟連結好像可以分兩張票？

**Comment by koten0224** [comment]
> 弄圖片跟連結好像可以分兩張票？

可以啊，你要接其中一張嗎XD
