### ISSUE TITLE
Channel 新增修改刪除功能(#41)

### ISSUE THREAD

**Issue by koten0224** [DC7806/Goodbytes#31]
#### controller `Channels`
- [x]  限定organization admin使用
- [x] generate controller channels
  - [x] create: 新增channel
    - [x] 新增後自動把organization admin加入到channel as channel admin
    - [x] Channel model: validates :name presence: true
  - [x] update: 修改channel，目前能改的好像也只有名稱，新增文章是article controller要做的事
  - [x] destroy: 刪除channel，連帶的底下的article也會一起被刪掉

#### controller `Channel_roles`
- [x] 限定Channel Admin使用
- [x] generate controller channel_roles
  - [x] create: 給予成員對channel的權限，admin or member
  - [x] update: 更改成員或自己的權限
  - [x] destroy: 將成員趕出channel，包括自己也可以退出

**Comment by RocketSH** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/57695762/81794636-a90d8280-953d-11ea-98a0-c3745315f870.png">
