### ISSUE TITLE
Generate Article Model& Controller

### ISSUE THREAD

**Issue by RocketSH** [DC7806/Goodbytes#34]
### Add model

- [x] Generate model: `Article`
- [x] Current.channel  in dashboard 
- [x] Sidebar channel link

### Add ArticlesController
- [x] generate controller: 
    - [x] index： channel/:id/articles  (article index in channel show)
    - [x] new： 新增article頁面
    - [x] create: 把新article寫到資料庫
    - [x] show：get單一篇article頁面
    - [x] edit: get編輯article頁面
    - [x] update: 把更新寫進資料庫
    - [x] destroy: 從資料庫刪除article

**Comment by koten0224** [comment]
我們的網站模式會比較像是，當點進單篇文章頁面時，那個頁面會同時兼show跟edit功能（參考goodbit）new方法也會到同一個模版，只是是空的
