### ISSUE TITLE
Upgrade Rails to 6.0.3.1 for security fixes

### ISSUE THREAD

**Issue by DC7806** [DC7806/Goodbytes#85]
https://weblog.rubyonrails.org/2020/5/18/Rails-5-2-4-3-and-6-0-3-1-have-been-released

**Comment by DC7806** [comment]
@RocketSH @koten0224 @ErenWeng 請安排升級 Rails 版本

**Comment by koten0224** [comment]
這個網址看不懂
給一堆checksums我要貼在哪邊嗎？
